[font]
size = 14
[font.offset]
x = -1
y = 2
[font.normal]
style = "semibold"
family = "SFMono"

[font.bold]
style = "bold"
family = "SFMono"

[font.italic]
style = "italic"
family = "SFMono"

[terminal.shell]
program = "zsh"

[window]
dynamic_padding = true
[window.padding]
x = 5
y = 5
