[font]
size = 14
[font.offset]
x = 0
y = 2
[font.normal]
style = "normal"
family = "iMWritingMono Nerd Font"

[font.bold]
style = "bold"
family = "iMWritingMono Nerd Font"

[font.italic]
style = "normal"
family = "iMWritingMono Nerd Font"

[terminal.shell]
program = "fish"
